import '../styles/Global.css'
import NavBar from '../components/NavBar'
import Head from 'next/head'
import { AppProps } from 'next/app'
import React from 'react'

export default function App({ Component, pageProps }: AppProps) {
  return <>
    <Head>
          <title>Bad Engine INC.</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/logo.png" />
    </Head>
    <NavBar></NavBar>
    <Component {...pageProps} />
  </> 
}   